# This file contains all settings for PSO (Particle swarm optimization)
---
# Enable/disable detailed info about every bee
enableBeeLog: false
# Dimentions
N: 2
# Amount of iterations
nIterations: 200
# Amount of bees
nBees: 5
# Bee's best position coefficient
pCoef: 0.5
# Swarm's best position coefficient
gCoef: 0.5
# Velocity coefficient
vCoef: 0.5
min1: -10
max1: 10
min2: -10
max2: 10
